user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    access_log off;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    # 灰度发布 upstream，ip_hash 保证会话一致性，weight 控制灰度比例
    upstream unnamed_api_backend {
        ip_hash;
        server host.containers.internal:5000 weight=90;
        server host.containers.internal:5001 weight=10;
    }

    server {
        listen 80;
        listen [::]:80;
        server_name xxx.com;

        location /api {
            proxy_pass http://unnamed_api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket 支持配置
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_connect_timeout 10s;
            proxy_read_timeout 60s;
        }
    }
}